version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: golang.org/x/sync
        versions:
          - ">= 0.20.0"
      - dependency-name: google.golang.org/grpc
        versions:
          - ">= 1.81.0"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
