run:
  timeout: 3m
  tests: true
linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - gosimple
    - revive
    - staticcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
